pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'  // Set your AWS region
        your-account-id = '686255964186'
        ECR_REPOSITORY = 'sample'  
        ECS_CLUSTER = 'new-app'  
        ECS_SERVICE = 'demoservice'  
        TASK_DEFINITION_FILE = 'new-app' 
        IMAGE_TAG = "${env.BUILD_NUMBER}" 
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def image = "${your-account-id}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}"
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin your-account-id.dkr.ecr.${AWS_REGION}.amazonaws.com
                        docker build -t ${image} .
                        docker push ${image}
                    """
                }
            }
        }

        // stage('Update Task Definition') {
        //     steps {
        //         script {
        //             def newTaskDef = sh(script: """
        //                 aws ecs describe-task-definition --task-definition your-task-definition-name \
        //                 --query 'taskDefinition' | jq '.containerDefinitions[0].image = "your-account-id.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}"' > ${TASK_DEFINITION_FILE}
        //                 aws ecs register-task-definition --cli-input-json file://${TASK_DEFINITION_FILE} | jq -r '.taskDefinition.taskDefinitionArn'
        //             """, returnStdout: true).trim()
                    
        //             echo "Updated Task Definition ARN: ${newTaskDef}"
        //         }
        //     }
        // }

        // stage('Deploy to ECS') {
        //     steps {
        //         script {
        //             sh """
        //                 aws ecs update-service --cluster ${ECS_CLUSTER} --service ${ECS_SERVICE} --task-definition your-task-definition-name
        //             """
        //         }
        //     }
        // }
    }
}
